

DELETE http://localhost:3001/api/persons/6126a9ef68e2b3210825b951

###

GET http://localhost:3001

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "{{$randomInt 101 10000}}",
    "number": "{{$randomInt 1000000 10000000}}"
}

###

PUT http://localhost:3001/api/persons/6126af3896d103135cf04600
Content-Type: application/json

{
    "name": "moi",
    "number": "3322222"
}






###

GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Test of Wrath {{$randomInt 1 100}}",
  "author": "TT",
  "url": "ex.ample",
  "likes": "{{$randomInt 1000000 10000000}}"
}

###