GET https://example.com/comments/1 HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1

###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### 
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/1 

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "{{$randomInt 10 10000}}",
    "number": "{{$randomInt 10 10000}}"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Sample",
    "number": "1212"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Sample",
    "number": "22"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Dimpl",
    "number": "22"
}